ramda/ramda-fantasy

.gitignore
package.json
src/IO.js
src/Reader.js
test/maybe.test.js

All existing tests can now be executed by running npm test. Mocha was
installed as a devDependency and is used by the npm test script.
The IO type depends on ramda and because of this ramda was installed
as a dependency. This could later be removed if the purpose is to make
this package dependency free.
A .gitignore file was created which includes the node_modules folder.

Make all existing tests run

---

test/future.test.js

Simple tests for .map and .chan functions in Future. Also modified the
.equals function to give better error messages in case of failure.

Add tests for Future .map and .chain

---

src/Reader.js

The `run` method on the Reader prototype was only delegating to the
internal function supplied to the constructor. A better solution for
this is to simply name the input function `run`. No need to use
`fn.call(this, arguments)`. Tests still pass.

Remove run from Reader prototype and make it an instance attribute

---

src/Reader.js

Don't merge this yet.
So, the tests pass before and after this change, but this is a fairly huge change as far as semantics go. Before, it wasn't a `Functor`, `Apply`, `Chain`, or `Monad` (as all of the functions depended on `chain` working properly), now it "should" be. I say "should" because I'm not actually sure this fix actually fixed it. This tells me that the tests aren't actually testing the semantics here, so we should discuss what should change such that the tests work properly.
I have not looked at the tests yet to see where the failure is. Maybe someone can provide some insight.

Fix `Reader`.

---

package.json
src/Future.js
test/future.test.js

This change to `ap` for Futures does not wait for its own fork to be
resolved before forking the input furture. The effect is, among other
things, that `lift` can be used in order to call a method with the
result of several futures that have been resolved in parallel.

Make Future.ap run in parallel

---

src/Future.js
test/future.test.js

Complement function to `of`. Creates a future that will be rejected with
the input value.

Add reject to Future

---

index.js
src/lift2.js
src/lift3.js
test/lift2.test.js
test/lift3.test.js

The lift function specifically implemented for fantasy land compatible
types. Comes in two versions, for functions of airity 2 and 3.

Add liftA2 and liftA3

---

test/future.test.js

The test always fails for me because it apparently just won't finish within the 20ms timeout. Raising it to 25ms fixed it for me and since 2*15 > 25 this stills proofs non-sequential execution.

Loosen up timeout for Future#ap parallel test

---

src/Either.js
src/Future.js
src/IO.js
src/Identity.js
src/Maybe.js
src/Reader.js
src/Tuple.js
test/either.test.js
test/future.test.js
test/identity.test.js
test/io.test.js
test/maybe.test.js
test/reader.test.js
test/tuple.test.js

This makes ramda-fantasy types compatible with [`R.toString`][1].
Should I update this pull request to remove the `show` method from __Tuple.js__?
[1]: http://ramdajs.com/docs/#toString

define "toString" method for each constructor

---

src/Future.js
test/future.test.js

e.g. If you make a ajax request and you want to process error data differently than success data.
This is Task::orElse in folktale's data.task

Adding chainReject for chaining operations off of failure cases. 

---

src/Future.js
test/future.test.js

When futures are forked, if the fork function throws a synchronous error
it is now caught and passed to the reject function.

Catch errors thrown in the fork function

---

src/Reader.js
test/reader.test.js
test/types.js

Not sure if there is interest in going down the transformer path or not, but I ended up with this after wanting a Reader/Future combo.
An example:
```js
var Reader = require('./src/Reader'),
Future = require('./src/Future'),
ReaderTFuture = Reader.T(Future);
var log = console.log.bind(console);
var delay = d => Future((_, done) => setTimeout(done, d));
var delayedText = ReaderTFuture.ask.chain(env => 
ReaderTFuture.lift(delay(env.delay).map(() => env.text))
);
delayedText.run({ delay: 1000, text: 'Hello!' }).fork(log, log);
```
If desirable, we could also implement `Reader` via `Reader.T(Identity)`.
I'm not sure how useful this is in the JS space, so I would appreciate comments by anyone who has experience with using `ReaderT`s in general.

Adds Reader Transformer

---

package.json
src/IO.js
src/Reader.js
test/either.test.js
test/future.test.js
test/identity.test.js
test/io.test.js
test/maybe.test.js
test/reader.test.js
test/tuple.test.js
test/types.js
test/utils.js

- `types.js` tests now accept a custom equality function to be passed in.
- Bumps ramda version to 0.17
- [fix] `IO.chain` has been updated to pass on `arguments`
Fixes #63

Removes `equals` from `IO` and `Reader`.

---

src/Future.js
test/future.test.js

Cache is a more accurate description of what the function does.
I recently watched a video with Douglas Crockford where he points out the difference between memoization and caching and I realized that this function is more like the latter. Subsequent calls to the original function will not necessarily yield the same result.

Change name of memoize to cache

---

package.json

Test suite passes with 15, 16, 17 and 18

Update ramda version range to include 0.18.0

---

package.json
src/Either.js
test/either.test.js
test/types.js

- Either::ap now returns `this` for `Left` (fixes #75)
- ~~Either::extract added~~
- ~~Either::extend no longer returns `this` for `Left` to satisfy `extract . extend f = f`~~
- Either tests refactored to use JSVerify
- Comonad laws added to test/types.js

Various changes to Either

---

src/Future.js
test/future.test.js

I noticed Ramda Future wraps `fork` in a *try-catch*. I'm assuming this was done with the intention to automatically catch errors from throwing user functions. In a purely functional world that wouldn't make sense, but I can appreciate the idea that this protects users of Future from the rigors of multi-paradigm.
However, I think that Futures should either *have* this behaviour (like `bluebird`), or not have it at all (like `data.task`), but Ramda Futures have it "*sometimes*", as demonstrated by the following code (also added as unit test), and I think this is quite confusing:
```js
//The error is caught and handled by handler:
Future.of(1).map(throws).fork(handler, noop);
//The error escapes and destroys everything you ever loved:
delayedFutureOf(1).map(throws).fork(handler, noop);
``` …

Improve Future try-catching

---

src/Future.js

Switched many internal `fork` calls to `_fork` calls to reduce needless try-catch wrapping of internal functions that were never going to throw. Taken from [pull 79](https://github.com/ramda/ramda-fantasy/pull/79) where it was originally introduced.
The reason behind this change is that *try-catch-wrapping* [might cost some performance](https://jsperf.com/try-catch/7). I haven't actually tested this for performance gains, but I'd imagine that all that try-catch wrapping when using Future-heavy code might add up.

Reduce on unnecessary try-catch wrapping in Futures

---

test/future.test.js

Replace noops with the more correct `assert.fail` to ensure test failure
in the event that the reject callback is run.
See #85 for discussion.

Fix test semantics of reject for Future#ap

---

src/Either.js
src/Future.js
src/IO.js
src/Identity.js
src/Maybe.js
src/Reader.js
src/Tuple.js
test/either.test.js
test/future.test.js
test/identity.test.js
test/io.test.js
test/maybe.test.js
test/reader.test.js
test/tuple.test.js

This provides compatibility with `S.type`, added in plaid/sanctuary#105:
> #### `type :: a -> String`
>
> Takes a value, `x`, of any type and returns its type identifier. If `x` has a `'@@type'` property whose value is a string, `x['@@type']` is the type identifier. Otherwise, the type identifier is the result of applying [`R.type`][1] to `x`.
>
> `'@@type'` properties should use the form `'<package-name>/<type-name>'`, where `<package-name>` is the name of the npm package in which the type is defined.
>
> ```javascript
> > S.type(S.Just(42))
> 'sanctuary/Maybe'
>
> > S.type([1, 2, 3])
> 'Array'
> ```
[1]: http://ramdajs.com/docs/#type

specify "@@type" property for each type

---

docs/State.md
index.js
src/State.js
src/internal/util.js
test/state.test.js

As per #91, this change introduces the `State` type and `StateT` transformer.
Docs can be viewed here: https://github.com/scott-christopher/ramda-fantasy/blob/state/docs/State.md

Adds State type

---

src/Reader.js

Following on from #93, `equals` doesn't make sense in the context of a `Reader`/`ReaderT`.

Removes equals from ReaderT

---

src/Either.js
src/Future.js
src/IO.js
src/Identity.js
src/Maybe.js
src/Reader.js
src/State.js
src/Tuple.js
src/internal/util.js
src/lift2.js
src/lift3.js

This commit comes from my need to use Maybe only as I do not need the rest. Thus,
I do `require('ramda-fantasy/src/Maybe')`. But the problem with the old way of doing require in `ramda-fantasy` is that tree shaking can not be performed.
Although only three functions are used in this module from `ramda`, the whole library (`ramda`) is included in my build through `ramda-fantasy`.
I use rollup in order to build my code as it can perform tree shaking. Thus, the features that are not required in my code are not included in build. However, dependencies
also need to include the only parts they need.

Fixed the way Ramda is required

---

docs/Reader.md

I see `ReaderT` being returned elsewhere so I assume these should return `ReaderT` as well.

docs/Reader: fix possibly incorrect type sigs

---

README.md

The currently recommended library has not been updated to use prefixed method names, so this should be uncontroversial. Still, I'd like to get approval from a contributor before merging this pull request.

readme: update recommended replacement for Identity type
