ramda/ramda-fantasy

test/types.js

test: simplify interface declaration

---

src/Maybe.js
src/internal/util.js
test/maybe.test.js

updates to Maybe from recent discussion on fantasy-land here https://github.com/fantasyland/fantasy-land/issues/85

data Maybe a = Just a | Nothing

---

README.md
package.json

Described the project status and how to access the types in the README
file.
Set project version to 0.1.0.
Upgraded ramda dependency to ^0.10.0

Add to readme and update package.json

---

src/Maybe.js
test/maybe.test.js

This adds the methods `get`, `isNothing` and `isSomething` on `Maybe`.
`get` on a `Just` returns the value inside. Get on a `Nothing` throws an
error.
`isNothing` returns true for `Nothing` instances and false for `Just`
instances. The opposite is true for `isSomething`.

Add Maybe getter methods

---

src/Either.js
test/either.test.js

This adds `bimap` to `Either` which takes two functions an applies the
first one to the left value if existing and the second one to the right
value if existing. Inspired by folktale.

Add bimap to Either

---

src/Future.js
test/future.test.js

Maps the first function over the rejected value of a Future and the
second function over a resolved value of a future.

Add bimap to future

---

package.json

Alternative to #41
```console
$ npm run release-{major,minor,patch}
```

automate release process

---

src/Either.js

Extend is trivial to implement for Either (as discussed on gitter.im with @joneshf )

Extend for Either

---

src/Either.js
test/either.test.js
test/types.js

- Fixes a jshint warning in Either.js
- Add tests for Either Extend tests

Either extend test

---

.jscsrc
.npmignore
package.json
src/Either.js
src/Future.js
src/IO.js
src/Identity.js
src/Maybe.js
src/Reader.js
src/Tuple.js
src/internal/util.js
test/either.test.js
test/future.test.js
test/identity.test.js
test/io.test.js
test/maybe.test.js
test/reader.test.js
test/tuple.test.js
test/types.js

The code currently uses two spaces in some places and four spaces in others.

style: use two spaces for indentation

---

README.md
src/Maybe.js
test/maybe.test.js
test/types.js

Example:
```js
// Maybe.maybe :: b -> (a -> b) -> Maybe a -> b
Maybe.maybe(42, x => 2 * x, Just(10));  // 20
Maybe.maybe(42, x => 2 * x, Nothing()); // 42
// Maybe.toArray :: Maybe a -> [a]
Maybe.toArray(Just(42));  // [42]
Maybe.toArray(Nothing()); // []
// Maybe m => m.reduce :: (z -> a -> z) -> z -> z
Just(32).reduce(R.add, 10);  // 42
Nothing().reduce(R.add, 10); // 10
```

Adds reduce, maybe and toArray to Maybe

---

src/Future.js
test/future.test.js

Memoize wraps a `Future` and returns a new `Future` that guarantees
that the inner `Future` will only be forked once. Later forkings will
callback with the cached resolved value or error. If the memoized
`Future` is forked several times before it has been resolved, all
callbacks will be fired once the asynchronous operation is completed.
Apart from feedback on the code, I am open for a discussion on whether this should be a part of ramda-fantasy, or not and if the placement of the function is good or if it should have its own separate file.

Add Future.Memoize

---

src/lift2.js
src/lift3.js

Since #45 seems to be stuck I took care of this myself.

Fix incorrect name in lift functions

---

src/Reader.js
test/reader.test.js

Fixes Reader.ask

---

README.md
docs/Either.md
docs/Future.md
docs/IO.md
docs/Identity.md
docs/Maybe.md
docs/Reader.md
docs/Tuple.md

It's here :smile: ... at least a first draft anyway.
I welcome plenty of feedback, as writing is definitely not a strong point of mine.
I've only captured the data types in this batch, but I would like to add more general docs on the different implemented specs at some point.

Docs - first draft

---

package.json
test/future.test.js

Update dependency on Ramda to work with 0.19.

Allow Ramda 0.19

---

docs/Either.md
src/Either.js
test/either.test.js

How do you feel about adding a `Either.isLeft` and a `Either.isRight`?
Similarly to `Maybe.isJust` it can be called on an instance or as a static method.
Let me know if I need to change something.

adds Either.isLeft/isRight

---

package.json

Update ramda dependency range to include all patch releases of 0.19.
Closes #95

Update ramda dependency range to include 0.19.x

---

docs/Future.md

Fixing a typo in the Future documentation.

Fix word typo

---

README.md

Since it was missing. I based the checkmarks on the docs, let me know if I got something wrong.

Add State to Table on README

---

src/Either.js
test/either.test.js

Fixed #150 
I also removed the `Either.equals` static property.

Fix Either#equals() implementation

---

docs/Either.md
src/Either.js
test/either.test.js

In reference to the comment made by @OliverJAsh on [#153](https://github.com/ramda/ramda-fantasy/issues/153) I thought it might be a simple addition and interesting one to have on the either prototype.

Either instance 'either' method

---

docs/Maybe.md
src/Maybe.js
test/maybe.test.js

In the interest of continuing on to wrap up open PRs for #157, this PR contains the changes from #133 with minor tweaks as per the feedback provided.

Adds Maybe.toMaybe

---

README.md

Hello, I'm in the process of translating the documentation of types into Spanish, there are already several types translated. I hope they can accept the PR, greetings to all :)

Translation to spanish
